GH Actions: Added support for code coverage with Coveralls.io
php-parallel-lint/PHP-Console-Color pull request #30
Opened 2022-01-28 08:17 UTC by grogy

2022-01-28 09:17 UTC, jrfnl requested changes
@grogy Nicely done. I've left some comments inline to simplify things a bit.

2022-01-28 09:17 UTC, jrfnl commented on .github/workflows/test.yml
> +        experimental: [ false ]
As the intention is to only run the code coverage on one PHP version, you may as well remove the whole `matrix` and just add `'7.4'` directly to `setup-php`.

2022-01-28 09:17 UTC, jrfnl commented on .github/workflows/test.yml
> +          php-version: ${{ matrix.php }}
```suggestion
          php-version: '7.4'
```

2022-01-28 09:17 UTC, jrfnl commented on .github/workflows/test.yml
> +          COVERALLS_FLAG_NAME: php-${{ matrix.php }}-phpcs-${{ matrix.phpcs_version }}
As you are only running one build (PHP 7.4) for code coverage, no need to set the "parallel" flag or to name the builds as for each push/PR, there will only ever be one.

Also see: https://github.com/php-coveralls/php-coveralls#parallel-builds

This also means that the complete `coveralls-finish` job shouldn't be needed.

2022-01-28 09:17 UTC, jrfnl commented on .github/workflows/test.yml
> +        run: vendor/bin/phpunit
```suggestion
        run: composer coverage
```

By using the Composer script, if this command would get additional arguments at some point, those only need to be maintained in one place.

2022-01-28 09:17 UTC, jrfnl commented on .github/workflows/test.yml
> +          parallel-finished: true
This part shouldn't be needed without parallel builds.

2022-02-04 11:56 UTC, grogy commented
Thanks for the comments. Configuration is now so simple! :D It is so much better.

Please, can you check current changeset?

2022-02-08 17:44 UTC, jrfnl approved these changes
Looks good to me!

Only thing we could still consider for change is to remove PHP `7.4` from the normal test job as the tests on that PHP version are now being run twice, which isn't really needed.
All the same, that's not a blocker for merging. Can always still be done later.

2022-02-08 17:44 UTC, merged

2022-02-08 22:53 UTC, jrfnl commented
Darn! I keep forgetting to use "rebase & merge". I'll have a look at the settings if it can be enforced. => Done!

On that note: Could you turn on "Auto delete merged branches" (for all repos) ? Seems I don't have access to that setting.

2022-02-09 04:19 UTC, grogy commented
> I'll have a look at the settings if it can be enforced. => Done!
Perfect, I set it on all another repositories.

> Could you turn on "Auto delete merged branches" (for all repos) ?
Yes, sure :-) Done on all repositories

> Only thing we could still consider for change is to remove PHP 7.4 from the normal test job...
I am adding issue https://github.com/php-parallel-lint/PHP-Console-Color/issues/31

Thank you :-)

2022-02-09 08:18 UTC, jrfnl commented
Thanks @grogy !